name: Publish Python distributions to PyPI

on:
  release:
    types: [created]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build-n-publish:
    name: Build an publish Python distributions to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install a specific version of uv.
        version: "0.7.7"

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Install dependencies
      run: uv pip install setuptools wheel twine

    - name: Build a binary wheel and a source tarball
      run: uv build sdist bdist_wheel

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      run: uv publish
